// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "fio-service/internal/model"

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// SendFio provides a mock function with given fields: ctx, fio, reason
func (_m *Publisher) SendFio(ctx context.Context, fio model.Fio, reason string) error {
	ret := _m.Called(ctx, fio, reason)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Fio, string) error); ok {
		r0 = rf(ctx, fio, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
