// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "fio-service/internal/model"

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// SendFio provides a mock function with given fields: fio, reason
func (_m *Publisher) SendFio(fio model.Fio, reason string) {
	_m.Called(fio, reason)
}
